name: cs_100
description: A project focused on helping computer science students at KNUST

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dartz: ^0.10.1
  google_fonts: ^3.0.1
  flex_color_scheme: ^6.0.1
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  ionicons: ^0.2.1
  device_preview: ^1.1.0
  flutter_native_splash: ^2.2.14
  get_storage: ^2.0.3
  # share_plus: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
